<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFFPvJuD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFFPvJuD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFFPvJuD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFFPvJuD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFFPvJuD\App_KernelDevDebugContainer([
    'container.build_hash' => 'FFPvJuD',
    'container.build_id' => '19374602',
    'container.build_time' => 1612563649,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFFPvJuD');
