<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKl54CDi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKl54CDi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKl54CDi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKl54CDi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKl54CDi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kl54CDi',
    'container.build_id' => '1601b267',
    'container.build_time' => 1612710166,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKl54CDi');
