<?php

namespace ContainerKl54CDi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RS_M6aEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RS.m6aE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RS.m6aE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ronda' => ['privates', '.errored..service_locator.RS.m6aE.App\\Entity\\Ronda', NULL, 'Cannot autowire service ".service_locator.RS.m6aE": it references class "App\\Entity\\Ronda" but no such service exists.'],
            'torneigRepository' => ['privates', 'App\\Repository\\TorneigRepository', 'getTorneigRepositoryService', true],
        ], [
            'ronda' => 'App\\Entity\\Ronda',
            'torneigRepository' => 'App\\Repository\\TorneigRepository',
        ]);
    }
}
