<?php

namespace ContainerKl54CDi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournAddJugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TournAddJug' shared autowired service.
     *
     * @return \App\Form\TournAddJug
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TournAddJug.php';

        return $container->privates['App\\Form\\TournAddJug'] = new \App\Form\TournAddJug();
    }
}
