<?php

namespace ContainerCjKLBZn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTorneigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.657b3tR.App\Entity\Torneig' shared service.
     *
     * @return \App\Entity\Torneig
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.657b3tR": it references class "App\\Entity\\Torneig" but no such service exists.');
    }
}
