<?php

namespace ContainerEajhxBH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJugador2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ptI9rup.App\Entity\Jugador' shared service.
     *
     * @return \App\Entity\Jugador
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ptI9rup": it references class "App\\Entity\\Jugador" but no such service exists.');
    }
}
