<?php

namespace ContainerA1qVI6N;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DUnTj19Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DUnTj19' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DUnTj19'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ronda' => ['privates', '.errored..service_locator.DUnTj19.App\\Entity\\Ronda', NULL, 'Cannot autowire service ".service_locator.DUnTj19": it references class "App\\Entity\\Ronda" but no such service exists.'],
        ], [
            'ronda' => 'App\\Entity\\Ronda',
        ]);
    }
}
