<?php

namespace ContainerFFPvJuD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EDW3bs1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EDW3bs1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EDW3bs1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'securityController' => ['services', 'App\\Controller\\SecurityController', 'getSecurityControllerService', true],
        ], [
            'securityController' => 'App\\Controller\\SecurityController',
        ]);
    }
}
