<?php

namespace ContainerFFPvJuD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IhHg9h8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IhHg9h8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IhHg9h8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'torneig' => ['privates', '.errored..service_locator.IhHg9h8.App\\Entity\\Torneig', NULL, 'Cannot autowire service ".service_locator.IhHg9h8": it references class "App\\Entity\\Torneig" but no such service exists.'],
        ], [
            'torneig' => 'App\\Entity\\Torneig',
        ]);
    }
}
