<?php

namespace ContainerZS9evU0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tj2DXapService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tj2DXap' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tj2DXap'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jugador' => ['privates', '.errored..service_locator.tj2DXap.App\\Entity\\Jugador', NULL, 'Cannot autowire service ".service_locator.tj2DXap": it references class "App\\Entity\\Jugador" but no such service exists.'],
            'torneigRepository' => ['privates', 'App\\Repository\\TorneigRepository', 'getTorneigRepositoryService', true],
        ], [
            'jugador' => 'App\\Entity\\Jugador',
            'torneigRepository' => 'App\\Repository\\TorneigRepository',
        ]);
    }
}
