<?php

namespace Container3xzwcp4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJugadorTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\JugadorType' shared autowired service.
     *
     * @return \App\Form\JugadorType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/JugadorType.php';

        return $container->privates['App\\Form\\JugadorType'] = new \App\Form\JugadorType();
    }
}
